# CADASTRAR NOME DE DEPARTAMENTO NA TABELA DE DEPARTAMENTO

INSERT INTO MC_DEPTO (CD_DEPTO, NM_DEPTO, ST_DEPTO)
VALUES (1,'COMERCIAL','A'),
(2,'CONTABILIDADE','A'),
(3,'ESTOQUE','A'),
(4,'FINANCEIRO','A'),
(5,'SAC','A'),
(6,'RECURSOS_HUMANOS','A'),
(7,'LOGISTICA','A');